#!/bin/bash
rm -rf /etc/X11/xorg.conf.d/40-libinput.conf
cp -rf ./boot/config-35-480X320.txt /boot/config.txt
if [ -b /dev/mmcblk0p7 ]; then
cp ./usr/cmdline.txt-noobs /boot/cmdline.txt
else
cp ./usr/cmdline.txt /boot/
fi
cp ./usr/inittab /etc/
cp -rf ./usr/99-fbturbo.conf-HDMI /usr/share/X11/xorg.conf.d/99-fbturbo.conf
mkdir -p /etc/X11/xorg.conf.d
cp -rf ./usr/99-calibration.conf-3508 /etc/X11/xorg.conf.d/99-calibration.conf
nodeplatform=`uname -n`
kernel=`uname -r`
version=`uname -v`
if test "$nodeplatform" = "raspberrypi";then
echo "this is raspberrypi kernel"
version=${version%% *}
version=${version#*#}
echo $version
if test $version -lt 970;then
echo "reboot"
else
echo "need to update touch configuration"
apt-get install xserver-xorg-input-evdev
cp -rf /usr/share/X11/xorg.conf.d/10-evdev.conf /usr/share/X11/xorg.conf.d/45-evdev.conf
echo "reboot"
fi
else
echo "this is not raspberrypi kernel, no need to update touch configure, reboot"
fi
reboot
